name: Publish

on:
  push:
    branches: [master]

permissions:
  contents: write

env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

jobs:
  publish:
    name: ⬣ Publish
    runs-on: ubuntu-latest
    steps:
      - name: 🛑 Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1

      - name: ⬇️ Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: ⎔ Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16.13.0

      - name: 📥 Download deps
        uses: bahmutov/npm-install@v1

      - name: Lint
        run: yarn lint

      - name: Build libs
        run: yarn build

      - name: Publish
        run: npx semantic-release
